#############################################################################
# Makefile for building: ququan_shapes
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  ququan_shapes.pro
# Template: subdirs
# Command: C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\qmake.exe -o Makefile ququan_shapes.pro -spec win32-msvc
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-main \
		sub-attach_tree \
		sub-layer \
		sub-muParser \
		sub-param \
		sub-pdk_manager \
		sub-primitive \
		sub-resources \
		sub-shape \
		sub-common \
		sub-ququan_layout_sample \
		sub-pymod


sub-main-qmake_all: sub-attach_tree-qmake_all sub-layer-qmake_all sub-param-qmake_all sub-shape-qmake_all sub-common-qmake_all sub-primitive-qmake_all sub-resources-qmake_all sub-muParser-qmake_all FORCE
	@if not exist main\ mkdir main\ & if not exist main\ exit 1
	cd main\ && $(QMAKE) -o Makefile D:\Work\ququan_shapes\main\main.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd main\ && $(MAKE) -f Makefile qmake_all
sub-main: $(MAKEFILE) sub-attach_tree \
		sub-layer \
		sub-param \
		sub-shape \
		sub-common \
		sub-primitive \
		sub-resources \
		sub-muParser FORCE
	@if not exist main\ mkdir main\ & if not exist main\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd main\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\main\main.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-main-make_first: sub-attach_tree-make_first sub-layer-make_first sub-param-make_first sub-shape-make_first sub-common-make_first sub-primitive-make_first sub-resources-make_first sub-muParser-make_first FORCE
	@if not exist main\ mkdir main\ & if not exist main\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd main\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\main\main.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-main-all: sub-attach_tree-all sub-layer-all sub-param-all sub-shape-all sub-common-all sub-primitive-all sub-resources-all sub-muParser-all FORCE
	@if not exist main\ mkdir main\ & if not exist main\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd main\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\main\main.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-main-clean: sub-attach_tree-clean sub-layer-clean sub-param-clean sub-shape-clean sub-common-clean sub-primitive-clean sub-resources-clean sub-muParser-clean FORCE
	@if not exist main\ mkdir main\ & if not exist main\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd main\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\main\main.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-main-distclean: sub-attach_tree-distclean sub-layer-distclean sub-param-distclean sub-shape-distclean sub-common-distclean sub-primitive-distclean sub-resources-distclean sub-muParser-distclean FORCE
	@if not exist main\ mkdir main\ & if not exist main\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd main\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\main\main.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-main-install_subtargets: sub-attach_tree-install_subtargets sub-layer-install_subtargets sub-param-install_subtargets sub-shape-install_subtargets sub-common-install_subtargets sub-primitive-install_subtargets sub-resources-install_subtargets sub-muParser-install_subtargets FORCE
	@if not exist main\ mkdir main\ & if not exist main\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd main\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\main\main.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-main-uninstall_subtargets: sub-attach_tree-uninstall_subtargets sub-layer-uninstall_subtargets sub-param-uninstall_subtargets sub-shape-uninstall_subtargets sub-common-uninstall_subtargets sub-primitive-uninstall_subtargets sub-resources-uninstall_subtargets sub-muParser-uninstall_subtargets FORCE
	@if not exist main\ mkdir main\ & if not exist main\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd main\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\main\main.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-attach_tree-qmake_all: sub-param-qmake_all sub-layer-qmake_all sub-shape-qmake_all FORCE
	@if not exist attach_tree\ mkdir attach_tree\ & if not exist attach_tree\ exit 1
	cd attach_tree\ && $(QMAKE) -o Makefile D:\Work\ququan_shapes\attach_tree\attach_tree.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd attach_tree\ && $(MAKE) -f Makefile qmake_all
sub-attach_tree: $(MAKEFILE) sub-param \
		sub-layer \
		sub-shape FORCE
	@if not exist attach_tree\ mkdir attach_tree\ & if not exist attach_tree\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd attach_tree\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\attach_tree\attach_tree.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-attach_tree-make_first: sub-param-make_first sub-layer-make_first sub-shape-make_first FORCE
	@if not exist attach_tree\ mkdir attach_tree\ & if not exist attach_tree\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd attach_tree\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\attach_tree\attach_tree.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-attach_tree-all: sub-param-all sub-layer-all sub-shape-all FORCE
	@if not exist attach_tree\ mkdir attach_tree\ & if not exist attach_tree\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd attach_tree\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\attach_tree\attach_tree.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-attach_tree-clean: sub-param-clean sub-layer-clean sub-shape-clean FORCE
	@if not exist attach_tree\ mkdir attach_tree\ & if not exist attach_tree\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd attach_tree\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\attach_tree\attach_tree.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-attach_tree-distclean: sub-param-distclean sub-layer-distclean sub-shape-distclean FORCE
	@if not exist attach_tree\ mkdir attach_tree\ & if not exist attach_tree\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd attach_tree\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\attach_tree\attach_tree.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-attach_tree-install_subtargets: sub-param-install_subtargets sub-layer-install_subtargets sub-shape-install_subtargets FORCE
	@if not exist attach_tree\ mkdir attach_tree\ & if not exist attach_tree\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd attach_tree\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\attach_tree\attach_tree.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-attach_tree-uninstall_subtargets: sub-param-uninstall_subtargets sub-layer-uninstall_subtargets sub-shape-uninstall_subtargets FORCE
	@if not exist attach_tree\ mkdir attach_tree\ & if not exist attach_tree\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd attach_tree\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\attach_tree\attach_tree.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-layer-qmake_all:  FORCE
	@if not exist layer\ mkdir layer\ & if not exist layer\ exit 1
	cd layer\ && $(QMAKE) -o Makefile D:\Work\ququan_shapes\layer\layer.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd layer\ && $(MAKE) -f Makefile qmake_all
sub-layer: $(MAKEFILE) FORCE
	@if not exist layer\ mkdir layer\ & if not exist layer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd layer\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\layer\layer.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-layer-make_first: FORCE
	@if not exist layer\ mkdir layer\ & if not exist layer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd layer\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\layer\layer.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-layer-all: FORCE
	@if not exist layer\ mkdir layer\ & if not exist layer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd layer\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\layer\layer.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-layer-clean: FORCE
	@if not exist layer\ mkdir layer\ & if not exist layer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd layer\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\layer\layer.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-layer-distclean: FORCE
	@if not exist layer\ mkdir layer\ & if not exist layer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd layer\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\layer\layer.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-layer-install_subtargets: FORCE
	@if not exist layer\ mkdir layer\ & if not exist layer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd layer\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\layer\layer.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-layer-uninstall_subtargets: FORCE
	@if not exist layer\ mkdir layer\ & if not exist layer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd layer\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\layer\layer.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-muParser-qmake_all:  FORCE
	@if not exist muParser\ mkdir muParser\ & if not exist muParser\ exit 1
	cd muParser\ && $(QMAKE) -o Makefile D:\Work\ququan_shapes\muParser\muParser.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd muParser\ && $(MAKE) -f Makefile qmake_all
sub-muParser: $(MAKEFILE) FORCE
	@if not exist muParser\ mkdir muParser\ & if not exist muParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd muParser\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\muParser\muParser.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-muParser-make_first: FORCE
	@if not exist muParser\ mkdir muParser\ & if not exist muParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd muParser\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\muParser\muParser.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-muParser-all: FORCE
	@if not exist muParser\ mkdir muParser\ & if not exist muParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd muParser\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\muParser\muParser.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-muParser-clean: FORCE
	@if not exist muParser\ mkdir muParser\ & if not exist muParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd muParser\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\muParser\muParser.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-muParser-distclean: FORCE
	@if not exist muParser\ mkdir muParser\ & if not exist muParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd muParser\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\muParser\muParser.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-muParser-install_subtargets: FORCE
	@if not exist muParser\ mkdir muParser\ & if not exist muParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd muParser\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\muParser\muParser.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-muParser-uninstall_subtargets: FORCE
	@if not exist muParser\ mkdir muParser\ & if not exist muParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd muParser\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\muParser\muParser.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-param-qmake_all: sub-muParser-qmake_all sub-common-qmake_all FORCE
	@if not exist param\ mkdir param\ & if not exist param\ exit 1
	cd param\ && $(QMAKE) -o Makefile D:\Work\ququan_shapes\param\param.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd param\ && $(MAKE) -f Makefile qmake_all
sub-param: $(MAKEFILE) sub-muParser \
		sub-common FORCE
	@if not exist param\ mkdir param\ & if not exist param\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd param\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\param\param.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-param-make_first: sub-muParser-make_first sub-common-make_first FORCE
	@if not exist param\ mkdir param\ & if not exist param\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd param\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\param\param.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-param-all: sub-muParser-all sub-common-all FORCE
	@if not exist param\ mkdir param\ & if not exist param\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd param\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\param\param.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-param-clean: sub-muParser-clean sub-common-clean FORCE
	@if not exist param\ mkdir param\ & if not exist param\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd param\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\param\param.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-param-distclean: sub-muParser-distclean sub-common-distclean FORCE
	@if not exist param\ mkdir param\ & if not exist param\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd param\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\param\param.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-param-install_subtargets: sub-muParser-install_subtargets sub-common-install_subtargets FORCE
	@if not exist param\ mkdir param\ & if not exist param\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd param\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\param\param.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-param-uninstall_subtargets: sub-muParser-uninstall_subtargets sub-common-uninstall_subtargets FORCE
	@if not exist param\ mkdir param\ & if not exist param\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd param\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\param\param.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-pdk_manager-qmake_all:  FORCE
	@if not exist pdk_manager\ mkdir pdk_manager\ & if not exist pdk_manager\ exit 1
	cd pdk_manager\ && $(QMAKE) -o Makefile D:\Work\ququan_shapes\pdk_manager\pdk_manager.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdk_manager\ && $(MAKE) -f Makefile qmake_all
sub-pdk_manager: $(MAKEFILE) FORCE
	@if not exist pdk_manager\ mkdir pdk_manager\ & if not exist pdk_manager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdk_manager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pdk_manager\pdk_manager.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-pdk_manager-make_first: FORCE
	@if not exist pdk_manager\ mkdir pdk_manager\ & if not exist pdk_manager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdk_manager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pdk_manager\pdk_manager.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-pdk_manager-all: FORCE
	@if not exist pdk_manager\ mkdir pdk_manager\ & if not exist pdk_manager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdk_manager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pdk_manager\pdk_manager.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-pdk_manager-clean: FORCE
	@if not exist pdk_manager\ mkdir pdk_manager\ & if not exist pdk_manager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdk_manager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pdk_manager\pdk_manager.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-pdk_manager-distclean: FORCE
	@if not exist pdk_manager\ mkdir pdk_manager\ & if not exist pdk_manager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdk_manager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pdk_manager\pdk_manager.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-pdk_manager-install_subtargets: FORCE
	@if not exist pdk_manager\ mkdir pdk_manager\ & if not exist pdk_manager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdk_manager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pdk_manager\pdk_manager.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-pdk_manager-uninstall_subtargets: FORCE
	@if not exist pdk_manager\ mkdir pdk_manager\ & if not exist pdk_manager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdk_manager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pdk_manager\pdk_manager.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-primitive-qmake_all: sub-attach_tree-qmake_all FORCE
	@if not exist primitive\ mkdir primitive\ & if not exist primitive\ exit 1
	cd primitive\ && $(QMAKE) -o Makefile D:\Work\ququan_shapes\primitive\primitive.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd primitive\ && $(MAKE) -f Makefile qmake_all
sub-primitive: $(MAKEFILE) sub-attach_tree FORCE
	@if not exist primitive\ mkdir primitive\ & if not exist primitive\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd primitive\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\primitive\primitive.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-primitive-make_first: sub-attach_tree-make_first FORCE
	@if not exist primitive\ mkdir primitive\ & if not exist primitive\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd primitive\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\primitive\primitive.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-primitive-all: sub-attach_tree-all FORCE
	@if not exist primitive\ mkdir primitive\ & if not exist primitive\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd primitive\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\primitive\primitive.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-primitive-clean: sub-attach_tree-clean FORCE
	@if not exist primitive\ mkdir primitive\ & if not exist primitive\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd primitive\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\primitive\primitive.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-primitive-distclean: sub-attach_tree-distclean FORCE
	@if not exist primitive\ mkdir primitive\ & if not exist primitive\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd primitive\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\primitive\primitive.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-primitive-install_subtargets: sub-attach_tree-install_subtargets FORCE
	@if not exist primitive\ mkdir primitive\ & if not exist primitive\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd primitive\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\primitive\primitive.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-primitive-uninstall_subtargets: sub-attach_tree-uninstall_subtargets FORCE
	@if not exist primitive\ mkdir primitive\ & if not exist primitive\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd primitive\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\primitive\primitive.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-resources-qmake_all:  FORCE
	@if not exist resources\ mkdir resources\ & if not exist resources\ exit 1
	cd resources\ && $(QMAKE) -o Makefile D:\Work\ququan_shapes\resources\resources.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd resources\ && $(MAKE) -f Makefile qmake_all
sub-resources: $(MAKEFILE) FORCE
	@if not exist resources\ mkdir resources\ & if not exist resources\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd resources\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\resources\resources.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-resources-make_first: FORCE
	@if not exist resources\ mkdir resources\ & if not exist resources\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd resources\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\resources\resources.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-resources-all: FORCE
	@if not exist resources\ mkdir resources\ & if not exist resources\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd resources\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\resources\resources.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-resources-clean: FORCE
	@if not exist resources\ mkdir resources\ & if not exist resources\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd resources\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\resources\resources.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-resources-distclean: FORCE
	@if not exist resources\ mkdir resources\ & if not exist resources\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd resources\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\resources\resources.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-resources-install_subtargets: FORCE
	@if not exist resources\ mkdir resources\ & if not exist resources\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd resources\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\resources\resources.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-resources-uninstall_subtargets: FORCE
	@if not exist resources\ mkdir resources\ & if not exist resources\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd resources\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\resources\resources.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-shape-qmake_all:  FORCE
	@if not exist shape\ mkdir shape\ & if not exist shape\ exit 1
	cd shape\ && $(QMAKE) -o Makefile D:\Work\ququan_shapes\shape\shape.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd shape\ && $(MAKE) -f Makefile qmake_all
sub-shape: $(MAKEFILE) FORCE
	@if not exist shape\ mkdir shape\ & if not exist shape\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd shape\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\shape\shape.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-shape-make_first: FORCE
	@if not exist shape\ mkdir shape\ & if not exist shape\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd shape\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\shape\shape.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-shape-all: FORCE
	@if not exist shape\ mkdir shape\ & if not exist shape\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd shape\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\shape\shape.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-shape-clean: FORCE
	@if not exist shape\ mkdir shape\ & if not exist shape\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd shape\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\shape\shape.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-shape-distclean: FORCE
	@if not exist shape\ mkdir shape\ & if not exist shape\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd shape\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\shape\shape.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-shape-install_subtargets: FORCE
	@if not exist shape\ mkdir shape\ & if not exist shape\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd shape\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\shape\shape.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-shape-uninstall_subtargets: FORCE
	@if not exist shape\ mkdir shape\ & if not exist shape\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd shape\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\shape\shape.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-common-qmake_all:  FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && $(QMAKE) -o Makefile D:\Work\ququan_shapes\common\common.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && $(MAKE) -f Makefile qmake_all
sub-common: $(MAKEFILE) FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\common\common.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-common-make_first: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\common\common.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-common-all: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\common\common.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-common-clean: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\common\common.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-common-distclean: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\common\common.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-common-install_subtargets: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\common\common.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-common-uninstall_subtargets: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\common\common.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-ququan_layout_sample-qmake_all:  FORCE
	@if not exist ququan_layout_sample\ mkdir ququan_layout_sample\ & if not exist ququan_layout_sample\ exit 1
	cd ququan_layout_sample\ && $(QMAKE) -o Makefile D:\Work\ququan_shapes\ququan_layout_sample\ququan_layout_sample.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ququan_layout_sample\ && $(MAKE) -f Makefile qmake_all
sub-ququan_layout_sample: $(MAKEFILE) FORCE
	@if not exist ququan_layout_sample\ mkdir ququan_layout_sample\ & if not exist ququan_layout_sample\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ququan_layout_sample\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\ququan_layout_sample\ququan_layout_sample.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-ququan_layout_sample-make_first: FORCE
	@if not exist ququan_layout_sample\ mkdir ququan_layout_sample\ & if not exist ququan_layout_sample\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ququan_layout_sample\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\ququan_layout_sample\ququan_layout_sample.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-ququan_layout_sample-all: FORCE
	@if not exist ququan_layout_sample\ mkdir ququan_layout_sample\ & if not exist ququan_layout_sample\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ququan_layout_sample\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\ququan_layout_sample\ququan_layout_sample.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-ququan_layout_sample-clean: FORCE
	@if not exist ququan_layout_sample\ mkdir ququan_layout_sample\ & if not exist ququan_layout_sample\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ququan_layout_sample\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\ququan_layout_sample\ququan_layout_sample.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-ququan_layout_sample-distclean: FORCE
	@if not exist ququan_layout_sample\ mkdir ququan_layout_sample\ & if not exist ququan_layout_sample\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ququan_layout_sample\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\ququan_layout_sample\ququan_layout_sample.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-ququan_layout_sample-install_subtargets: FORCE
	@if not exist ququan_layout_sample\ mkdir ququan_layout_sample\ & if not exist ququan_layout_sample\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ququan_layout_sample\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\ququan_layout_sample\ququan_layout_sample.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-ququan_layout_sample-uninstall_subtargets: FORCE
	@if not exist ququan_layout_sample\ mkdir ququan_layout_sample\ & if not exist ququan_layout_sample\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ququan_layout_sample\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\ququan_layout_sample\ququan_layout_sample.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-pymod-qmake_all: sub-param-qmake_all FORCE
	@if not exist pymod\ mkdir pymod\ & if not exist pymod\ exit 1
	cd pymod\ && $(QMAKE) -o Makefile D:\Work\ququan_shapes\pymod\pymod.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pymod\ && $(MAKE) -f Makefile qmake_all
sub-pymod: $(MAKEFILE) sub-param FORCE
	@if not exist pymod\ mkdir pymod\ & if not exist pymod\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pymod\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pymod\pymod.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-pymod-make_first: sub-param-make_first FORCE
	@if not exist pymod\ mkdir pymod\ & if not exist pymod\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pymod\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pymod\pymod.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-pymod-all: sub-param-all FORCE
	@if not exist pymod\ mkdir pymod\ & if not exist pymod\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pymod\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pymod\pymod.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-pymod-clean: sub-param-clean FORCE
	@if not exist pymod\ mkdir pymod\ & if not exist pymod\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pymod\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pymod\pymod.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-pymod-distclean: sub-param-distclean FORCE
	@if not exist pymod\ mkdir pymod\ & if not exist pymod\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pymod\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pymod\pymod.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-pymod-install_subtargets: sub-param-install_subtargets FORCE
	@if not exist pymod\ mkdir pymod\ & if not exist pymod\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pymod\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pymod\pymod.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-pymod-uninstall_subtargets: sub-param-uninstall_subtargets FORCE
	@if not exist pymod\ mkdir pymod\ & if not exist pymod\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pymod\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pymod\pymod.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall

Makefile: ququan_shapes.pro C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\win32-msvc\qmake.conf C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\spec_pre.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\common\angle.conf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\common\windows-desktop.conf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\common\windows-vulkan.conf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\common\msvc-desktop.conf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\qconfig.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_charts.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_charts_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\qt_functions.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\qt_config.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\win32-msvc\qmake.conf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\exclusive_builds.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\common\msvc-version.conf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\toolchain.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\default_pre.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\win32\default_pre.prf \
		ququan_shapes.pri \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\resolve_config.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\default_post.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\precompile_header.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\warn_on.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\qmake_use.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\file_copies.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\win32\windows.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\testcase_targets.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\exceptions.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\yacc.prf \
		C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\lex.prf \
		ququan_shapes.pro
	$(QMAKE) -o Makefile ququan_shapes.pro -spec win32-msvc
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\spec_pre.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\common\angle.conf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\common\windows-desktop.conf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\common\windows-vulkan.conf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\common\msvc-desktop.conf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\qconfig.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_charts.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_charts_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_core.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_help.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_location.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_network.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmlmodels.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\qt_functions.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\qt_config.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\win32-msvc\qmake.conf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\spec_post.prf:
.qmake.stash:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\exclusive_builds.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\common\msvc-version.conf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\toolchain.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\default_pre.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\win32\default_pre.prf:
ququan_shapes.pri:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\resolve_config.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\default_post.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\precompile_header.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\warn_on.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\qmake_use.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\file_copies.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\win32\windows.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\testcase_targets.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\exceptions.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\yacc.prf:
C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\mkspecs\features\lex.prf:
ququan_shapes.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ququan_shapes.pro -spec win32-msvc

qmake_all: sub-main-qmake_all sub-attach_tree-qmake_all sub-layer-qmake_all sub-muParser-qmake_all sub-param-qmake_all sub-pdk_manager-qmake_all sub-primitive-qmake_all sub-resources-qmake_all sub-shape-qmake_all sub-common-qmake_all sub-ququan_layout_sample-qmake_all sub-pymod-qmake_all FORCE

make_first: sub-main-make_first sub-attach_tree-make_first sub-layer-make_first sub-muParser-make_first sub-param-make_first sub-pdk_manager-make_first sub-primitive-make_first sub-resources-make_first sub-shape-make_first sub-common-make_first sub-ququan_layout_sample-make_first sub-pymod-make_first  FORCE
all: sub-main-all sub-attach_tree-all sub-layer-all sub-muParser-all sub-param-all sub-pdk_manager-all sub-primitive-all sub-resources-all sub-shape-all sub-common-all sub-ququan_layout_sample-all sub-pymod-all  FORCE
clean: sub-main-clean sub-attach_tree-clean sub-layer-clean sub-muParser-clean sub-param-clean sub-pdk_manager-clean sub-primitive-clean sub-resources-clean sub-shape-clean sub-common-clean sub-ququan_layout_sample-clean sub-pymod-clean  FORCE
distclean: sub-main-distclean sub-attach_tree-distclean sub-layer-distclean sub-muParser-distclean sub-param-distclean sub-pdk_manager-distclean sub-primitive-distclean sub-resources-distclean sub-shape-distclean sub-common-distclean sub-ququan_layout_sample-distclean sub-pymod-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-main-install_subtargets sub-attach_tree-install_subtargets sub-layer-install_subtargets sub-muParser-install_subtargets sub-param-install_subtargets sub-pdk_manager-install_subtargets sub-primitive-install_subtargets sub-resources-install_subtargets sub-shape-install_subtargets sub-common-install_subtargets sub-ququan_layout_sample-install_subtargets sub-pymod-install_subtargets FORCE
uninstall_subtargets: sub-main-uninstall_subtargets sub-attach_tree-uninstall_subtargets sub-layer-uninstall_subtargets sub-muParser-uninstall_subtargets sub-param-uninstall_subtargets sub-pdk_manager-uninstall_subtargets sub-primitive-uninstall_subtargets sub-resources-uninstall_subtargets sub-shape-uninstall_subtargets sub-common-uninstall_subtargets sub-ququan_layout_sample-uninstall_subtargets sub-pymod-uninstall_subtargets FORCE

sub-main-debug: sub-attach_tree-debug sub-layer-debug sub-param-debug sub-shape-debug sub-common-debug sub-primitive-debug sub-resources-debug sub-muParser-debug
	@if not exist main\ mkdir main\ & if not exist main\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd main\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\main\main.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
sub-attach_tree-debug: sub-param-debug sub-layer-debug sub-shape-debug
	@if not exist attach_tree\ mkdir attach_tree\ & if not exist attach_tree\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd attach_tree\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\attach_tree\attach_tree.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
sub-layer-debug:
	@if not exist layer\ mkdir layer\ & if not exist layer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd layer\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\layer\layer.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
sub-muParser-debug:
	@if not exist muParser\ mkdir muParser\ & if not exist muParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd muParser\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\muParser\muParser.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
sub-param-debug: sub-muParser-debug sub-common-debug
	@if not exist param\ mkdir param\ & if not exist param\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd param\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\param\param.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
sub-pdk_manager-debug:
	@if not exist pdk_manager\ mkdir pdk_manager\ & if not exist pdk_manager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdk_manager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pdk_manager\pdk_manager.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
sub-primitive-debug: sub-attach_tree-debug
	@if not exist primitive\ mkdir primitive\ & if not exist primitive\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd primitive\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\primitive\primitive.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
sub-resources-debug:
	@if not exist resources\ mkdir resources\ & if not exist resources\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd resources\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\resources\resources.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
sub-shape-debug:
	@if not exist shape\ mkdir shape\ & if not exist shape\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd shape\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\shape\shape.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
sub-common-debug:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\common\common.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
sub-ququan_layout_sample-debug:
	@if not exist ququan_layout_sample\ mkdir ququan_layout_sample\ & if not exist ququan_layout_sample\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ququan_layout_sample\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\ququan_layout_sample\ququan_layout_sample.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
sub-pymod-debug: sub-param-debug
	@if not exist pymod\ mkdir pymod\ & if not exist pymod\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pymod\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pymod\pymod.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
debug: sub-main-debug sub-attach_tree-debug sub-layer-debug sub-muParser-debug sub-param-debug sub-pdk_manager-debug sub-primitive-debug sub-resources-debug sub-shape-debug sub-common-debug sub-ququan_layout_sample-debug sub-pymod-debug

sub-main-release: sub-attach_tree-release sub-layer-release sub-param-release sub-shape-release sub-common-release sub-primitive-release sub-resources-release sub-muParser-release
	@if not exist main\ mkdir main\ & if not exist main\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd main\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\main\main.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
sub-attach_tree-release: sub-param-release sub-layer-release sub-shape-release
	@if not exist attach_tree\ mkdir attach_tree\ & if not exist attach_tree\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd attach_tree\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\attach_tree\attach_tree.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
sub-layer-release:
	@if not exist layer\ mkdir layer\ & if not exist layer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd layer\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\layer\layer.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
sub-muParser-release:
	@if not exist muParser\ mkdir muParser\ & if not exist muParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd muParser\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\muParser\muParser.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
sub-param-release: sub-muParser-release sub-common-release
	@if not exist param\ mkdir param\ & if not exist param\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd param\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\param\param.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
sub-pdk_manager-release:
	@if not exist pdk_manager\ mkdir pdk_manager\ & if not exist pdk_manager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdk_manager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pdk_manager\pdk_manager.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
sub-primitive-release: sub-attach_tree-release
	@if not exist primitive\ mkdir primitive\ & if not exist primitive\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd primitive\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\primitive\primitive.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
sub-resources-release:
	@if not exist resources\ mkdir resources\ & if not exist resources\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd resources\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\resources\resources.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
sub-shape-release:
	@if not exist shape\ mkdir shape\ & if not exist shape\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd shape\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\shape\shape.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
sub-common-release:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\common\common.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
sub-ququan_layout_sample-release:
	@if not exist ququan_layout_sample\ mkdir ququan_layout_sample\ & if not exist ququan_layout_sample\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ququan_layout_sample\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\ququan_layout_sample\ququan_layout_sample.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
sub-pymod-release: sub-param-release
	@if not exist pymod\ mkdir pymod\ & if not exist pymod\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pymod\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pymod\pymod.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
release: sub-main-release sub-attach_tree-release sub-layer-release sub-muParser-release sub-param-release sub-pdk_manager-release sub-primitive-release sub-resources-release sub-shape-release sub-common-release sub-ququan_layout_sample-release sub-pymod-release

sub-main-check: sub-attach_tree-check sub-layer-check sub-param-check sub-shape-check sub-common-check sub-primitive-check sub-resources-check sub-muParser-check
	@if not exist main\ mkdir main\ & if not exist main\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd main\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\main\main.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
sub-attach_tree-check: sub-param-check sub-layer-check sub-shape-check
	@if not exist attach_tree\ mkdir attach_tree\ & if not exist attach_tree\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd attach_tree\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\attach_tree\attach_tree.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
sub-layer-check:
	@if not exist layer\ mkdir layer\ & if not exist layer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd layer\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\layer\layer.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
sub-muParser-check:
	@if not exist muParser\ mkdir muParser\ & if not exist muParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd muParser\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\muParser\muParser.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
sub-param-check: sub-muParser-check sub-common-check
	@if not exist param\ mkdir param\ & if not exist param\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd param\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\param\param.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
sub-pdk_manager-check:
	@if not exist pdk_manager\ mkdir pdk_manager\ & if not exist pdk_manager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdk_manager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pdk_manager\pdk_manager.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
sub-primitive-check: sub-attach_tree-check
	@if not exist primitive\ mkdir primitive\ & if not exist primitive\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd primitive\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\primitive\primitive.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
sub-resources-check:
	@if not exist resources\ mkdir resources\ & if not exist resources\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd resources\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\resources\resources.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
sub-shape-check:
	@if not exist shape\ mkdir shape\ & if not exist shape\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd shape\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\shape\shape.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
sub-common-check:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\common\common.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
sub-ququan_layout_sample-check:
	@if not exist ququan_layout_sample\ mkdir ququan_layout_sample\ & if not exist ququan_layout_sample\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ququan_layout_sample\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\ququan_layout_sample\ququan_layout_sample.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
sub-pymod-check: sub-param-check
	@if not exist pymod\ mkdir pymod\ & if not exist pymod\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pymod\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pymod\pymod.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
check: sub-main-check sub-attach_tree-check sub-layer-check sub-muParser-check sub-param-check sub-pdk_manager-check sub-primitive-check sub-resources-check sub-shape-check sub-common-check sub-ququan_layout_sample-check sub-pymod-check

sub-main-benchmark: sub-attach_tree-benchmark sub-layer-benchmark sub-param-benchmark sub-shape-benchmark sub-common-benchmark sub-primitive-benchmark sub-resources-benchmark sub-muParser-benchmark
	@if not exist main\ mkdir main\ & if not exist main\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd main\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\main\main.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
sub-attach_tree-benchmark: sub-param-benchmark sub-layer-benchmark sub-shape-benchmark
	@if not exist attach_tree\ mkdir attach_tree\ & if not exist attach_tree\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd attach_tree\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\attach_tree\attach_tree.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
sub-layer-benchmark:
	@if not exist layer\ mkdir layer\ & if not exist layer\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd layer\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\layer\layer.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
sub-muParser-benchmark:
	@if not exist muParser\ mkdir muParser\ & if not exist muParser\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd muParser\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\muParser\muParser.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
sub-param-benchmark: sub-muParser-benchmark sub-common-benchmark
	@if not exist param\ mkdir param\ & if not exist param\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd param\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\param\param.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
sub-pdk_manager-benchmark:
	@if not exist pdk_manager\ mkdir pdk_manager\ & if not exist pdk_manager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pdk_manager\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pdk_manager\pdk_manager.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
sub-primitive-benchmark: sub-attach_tree-benchmark
	@if not exist primitive\ mkdir primitive\ & if not exist primitive\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd primitive\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\primitive\primitive.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
sub-resources-benchmark:
	@if not exist resources\ mkdir resources\ & if not exist resources\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd resources\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\resources\resources.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
sub-shape-benchmark:
	@if not exist shape\ mkdir shape\ & if not exist shape\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd shape\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\shape\shape.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
sub-common-benchmark:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\common\common.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
sub-ququan_layout_sample-benchmark:
	@if not exist ququan_layout_sample\ mkdir ququan_layout_sample\ & if not exist ququan_layout_sample\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ququan_layout_sample\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\ququan_layout_sample\ququan_layout_sample.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
sub-pymod-benchmark: sub-param-benchmark
	@if not exist pymod\ mkdir pymod\ & if not exist pymod\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd pymod\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Work\ququan_shapes\pymod\pymod.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
benchmark: sub-main-benchmark sub-attach_tree-benchmark sub-layer-benchmark sub-muParser-benchmark sub-param-benchmark sub-pdk_manager-benchmark sub-primitive-benchmark sub-resources-benchmark sub-shape-benchmark sub-common-benchmark sub-ququan_layout_sample-benchmark sub-pymod-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

